using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GameofLifedanielT
{
    class Lvlfunk
    {
        public string[,] Maps()
        {
            string[,] Mapone = new string[40, 40]
          {
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},
        {"Wand","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Hinw","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Hinw","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Wald","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Gift","Wald","Gift","Wald","Gift","Wald","Gras","Wass","Wass","Wass","Wass","Gras","Wass","Wass","Wass","Gras","Wand"},
        {"Wand","Gras","Hinw","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Heal","Wald","Wald","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Bomb","Heal","Wald","Gift","Wald","Gift","Wald","Gras","Wald","Gras","Wass","Gras","Gras","Gras","Gras","Wass","Schi","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Bomb","Wald","Gift","Wald","Gras","Wald","Gras","Wald","Gras","Wass","Gras","Wass","Wass","Wass","Wass","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Gift","Wald","Gras","Wald","Gras","Wald","Gras","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Wald","Wald","Gras","VTur","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wass","Gras","Wass","Wass","Wass","Wass","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Rock","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gift","Gift","Wald","Gras","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Wass","Gras","Wass","Keys","Gras","Gras","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Rock","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Heal","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Wald","Star","Wald","Wald","Gras","Hinw","Gras","Gift","Gras","Gift","Gras","Gift","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gift","Gras","Gras","Wald","Gras","Wald","Wald","Gras","Hinw","Gras","Gift","Gras","Gift","Gras","Gras","Gras","VTur","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gift","Gras","Gras","Wald","Gras","Wald","Wald","Gras","Hinw","Gras","Gift","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Gift","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Wald","Wald","Gras","Gras","Gift","Gras","Gift","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gift","Gras","Gift","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Wald","OTur","Wald","Wald","Wald","Wald","OTur","Wald","Wand"},
        {"Wand","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","OTur","Wald","Wald","Wald","Wald","OTur","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Hinw","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","OTur","Wald","Wald","Wald","OTur","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","OTur","Wald","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Wass","Wass","Wass","Wass","Wass","Schi","Wass","Wald","Gift","Wald","Gift","Wald","Gras","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Wass","Wass","Wass","Wass","Wass","Gras","Wass","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Wass","Gras","Gras","Gras","Gras","Gras","Wass","Wald","Wald","Gift","Wald","Gras","Wald","Gift","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Lmax","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wald","Gras","Wald","Gift","Wald","Gift","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","OTur","Wald","Wald","Wald","Wald","Wald","Wald","Wand"},
        {"Wand","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Heal","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Haus","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Keys","Gras","Gras","Gras","Gras","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Haus","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Wald","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Haus","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Haus","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gift","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Haus","Wass","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gift","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gift","Wald","Haus","Haus","Haus","Haus","Gras","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Gras","Gras","Gras","Haus","Wass","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Haus","Haus","Haus","Gras","Haus","Wass","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Haus","Haus","Haus","Gras","Haus","Wass","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Hinw","Gras","Gras","Gras","Wald","Gras","Gras","Haus","Ende","Haus","Haus","Haus","Haus","Gras","Haus","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},

          };
            return Mapone;
        }
        public string[,] Maps2()
        {
            string[,] Mapone = new string[40, 40]
          {
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},
        {"Wand","Wald","Wald","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Wand","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Kome","Schi","Wand"},
        {"Wand","Wald","Wald","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Wand","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Kome","Gras","Wand"},
        {"Wand","Wald","Wald","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Wand","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},   
        {"Wand","Wald","Heal","Gras","Gras","Pers","Gras","Gras","Gras","Gras","Gras","Wand","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},  
        {"Wand","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Pers","Wand","Wass","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},      
        {"Wand","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Star","Gras","Gras","OTur","Gras","Kome","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Haus","Haus","Haus","Haus","Pers","Gras","Gras","Gras","Gras","OTur","Gras","Kome","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Pers","Gras","Pers","Wand","Wass","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Gras","Gras","Gras","Gras","Gras","Haus","Haus","Haus","Gras","Wand","Wass","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Gras","Pers","Gras","Gras","Gras","Haus","Haus","Haus","Gras","Wand","Wass","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Swor","Haus","Gras","Gras","Gras","Haus","Haus","Haus","Gras","Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Gras","Gras","Gras","Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Ship","Ship","Ship","Ship","Ship","Ship","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Gras","Gras","Gras","Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Ship","Ende","Steg","Steg","Schi","Ship","Ship","Wass","Wass","Wass","Lava","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},   
        {"Wand","Wald","Haus","Haus","Haus","Gras","Gras","Pers","Gras","Gras","Gras","Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Ship","Pers","Steg","Steg","Heal","Ship","Ship","Wass","Wass","Wass","Lava","Lava","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Wand","Wand","Wand","OTur","OTur","Wand","Wand","Wand","Wand","Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Ship","Ship","Ship","Steg","Ship","Ship","Wass","Wass","Cave","Cave","Lava","Lava","Cave","Cave","Cave","Cave","Cave","Cave","Wand"},
        {"Wand","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Steg","Wass","Wass","Wass","Wass","Cave","Bode","Lava","Lava","Lava","Cave","Swor","Rock","Bode","Cave","Wand"},
        {"Wand","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Heal","Kome","Cave","Bode","Bode","Haus","Haus","Haus","Cave","Bode","Lava","Lava","Lava","Cave","Gift","Cave","Bode","Cave","Wand"},
        {"Wand","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Bode","Cave","Bode","Bode","Haus","Haus","Haus","Cave","Bode","Lava","Lava","Bode","Cave","Gift","Cave","Bode","Cave","Wand"},     
        {"Wand","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Bode","Cave","Bode","Bode","Bode","Haus","Bode","Cave","Bode","Lava","Lava","Bode","Cave","Gift","Cave","Bode","Cave","Wand"},      
        {"Wand","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Swor","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Bode","Cave","Cave","Bode","Bode","Pers","Bode","Cave","Bode","Lava","Lava","Bode","Cave","Gift","Cave","Bode","Cave","Wand"}, 
        {"Wand","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Gras","Pers","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Bode","Cave","Cave","Cave","Cave","Bode","Bode","Bode","Bode","Lava","Lava","Bode","Cave","Hinw","Cave","Bode","Cave","Wand"}, 
        {"Wand","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Bode","Bode","Bode","Bode","Cave","Bode","Bode","Bode","Bode","Bode","Lava","Bode","Bode","Bode","Bode","Bode","Cave","Wand"},    
        {"Wand","Wass","Wass","Hinw","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Cave","Cave","Cave","Bode","Cave","Cave","Cave","Cave","Bode","Bode","Lava","Lava","Bode","Bode","Bode","Bode","Cave","Wand"},       
        {"Wand","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Gift","Gift","Bode","Bode","Cave","Cave","Cave","Cave","Bode","Bode","Lava","Lava","Bode","Bode","Bode","Bode","Cave","Wand"},     
        {"Wand","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Cave","Bode","Bode","Bode","Bode","Cave","Cave","Cave","Cave","Cave","Bode","Lava","Lava","Lava","Bode","Heal","Bode","Cave","Wand"},     
        {"Wand","Wald","Gras","Wald","Wald","Wald","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Kome","Bode","Bode","Bode","Keys","Cave","Cave","Cave","Cave","Cave","Bode","Bode","Lava","Lava","Cave","Cave","Bode","Cave","Wand"},     
        {"Wand","Wald","Gras","Wald","Wald","Wald","Wald","Gras","Wald","Wald","Wald","Wald","Heal","Wald","Gift","Gift","Gift","Wald","Wald","Wald","Wald","Cave","Cave","Cave","Cave","Cave","Cave","Bode","Bode","Cave","Cave","Cave","Bode","Lava","Lava","Lava","Lava","Bode","Cave","Wand"},    
        {"Wand","Wald","Gras","Wald","Gras","Gras","Wald","Gras","Wald","Bomb","Gras","Dwal","Gras","Wald","Gras","Gras","Gras","Wald","Wald","Gift","Gift","Cave","Cave","Cave","Cave","Cave","Cave","Bode","Bode","Cave","Cave","Cave","Cave","Cave","Cave","Lava","Lava","Bode","Cave","Wand"},      
        {"Wand","Wald","Gras","Wald","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Gras","Gras","Hinw","Gras","Gras","Wald","Wald","Gras","Gras","Kome","Bode","Bode","Cave","Cave","Bode","Bode","Bode","Bode","Bode","Bode","Cave","Bode","Bode","Lava","Lava","Bode","Cave","Wand"},       
        {"Wand","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Gras","Gift","Cave","Bode","Bode","Cave","Cave","Bode","Gift","Gift","Gift","Bode","Bode","Cave","Bode","Bode","Bode","Bode","Bode","Cave","Wand"},      
        {"Wand","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Gras","Dorn","Gras","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gift","Cave","Bode","Bode","Bode","Bode","Bode","Gift","Gift","Gift","Gift","Bode","Hinw","Bode","Bode","Lava","Lava","Bode","Cave","Wand"},      
        {"Wand","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Gift","Gift","Gras","Gras","Cave","Bode","Bode","Bode","Bode","Bode","Gift","Gift","Gift","Bode","Bode","Hinw","Bode","Bode","Lava","Lava","Lava","Lava","Wand"},       
        {"Wand","Wald","Gras","Gras","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gift","Gift","Gras","Heal","Cave","Cave","Cave","Cave","Cave","Bode","Bode","Bode","Bode","Bode","Bode","Cave","Bode","Bode","Lava","Lava","Lava","Lava","Wand"},      
        {"Wand","Wald","Hinw","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Dwal","Wald","Wald","Wald","Wald","Wald","Wald","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Wand"},        
        {"Wand","Wald","Gras","Gras","Gras","Dorn","Dorn","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Gras","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Swor","Swor","Bomb","Heal","Wand"}, 
        {"Wand","Wald","Gras","Gras","Gras","Gras","Dorn","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Wald","Wald","Gras","Rock","Kome","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cave","Cave","Cave","Kome","VTur","Kome","Bode","Bode","Bode","Wand"},      
        {"Wand","Wald","Gras","Gras","Gras","Dorn","Dorn","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Cave","Bode","Cave","Cave","Cave","Cave","Cave","Bode","Bode","Bode","Bode","Bode","Bode","Cave","Bode","Bode","Bode","Bode","Wand"},     
        {"Wand","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Lmax","Bode","Schi","Schi","Wand"},
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},

          };
            return Mapone;
        }
        public string[,] Maps3()
        {
            string[,] Mapone = new string[40, 40]
          {
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},     
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Vill","Vill","Vill","Bush","GuaK","Gras","Gras","Bush","Cwal","Stra","Stra","Haus","Haus","Haus","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Bush","Stmk","Dach","Dach","Alta","Dach","PHea","Stmk","Bush","Chea","Wand"},
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Vill","Vill","Vill","Bush","Gras","Bush","Gras","Bush","Cwal","Stra","Stra","Haus","Bode","Bode","Bode","Bode","Haus","Haus","Stra","Stra","Stra","Bush","Stmk","Dach","Dach","Pers","Dach","Dach","Stmk","Bush","Stra","Wand"},  
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Vill","Vill","Vill","Pers","Plas","Plas","Plas","Stra","Cwal","Pers","Stra","Haus","Bto2","Haus","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Bush","Stmk","Dach","Bank","Dach","Bank","Dach","Stmk","Bush","Hinw","Wand"},    
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Vill","Vill","Ende","Hinw","Plas","Wass","Plas","Stra","Tga2","Hinw","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Pers","Bush","Stmk","Dach","Dach","Dach","Dach","Dach","Stmk","Bush","Hinw","Wand"},
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Vill","Vill","Vill","Pers","Plas","Plas","Plas","Stra","Cwal","Pers","Stra","Haus","Haus","Stra","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Bush","Stmk","Dach","Bank","Dach","Bank","Dach","Stmk","Bush","Stra","Wand"},    
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Vill","Vill","Vill","Bush","Gras","Bush","Gras","Bush","Cwal","Stra","Stra","ITur","Haus","Stra","Bto1","Bode","Pers","Haus","Stra","Stra","Stra","Bush","Stmk","Dach","Dach","Dach","Dach","Dach","Stmk","Bush","Stra","Wand"},       
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Vill","Vill","Vill","Bush","Gras","Gras","Gras","Bush","Cwal","Stra","Stra","Haus","Haus","Stra","Haus","Haus","TrKK","Haus","Stra","Stra","Stra","Bush","Stmk","Dach","Bank","Dach","Bank","Dach","Stmk","Bush","Stra","Wand"},  
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Haus","Haus","Stra","Stra","Stra","Bush","Stmk","Dach","Dach","Dach","Dach","Dach","Stmk","Bush","Stra","Wand"},      
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Haus","Haus","Haus","Haus","Stra","Stra","Cwal","Stra","Stra","Stra","Stra","Stra","Pers","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Bush","Stmk","Dach","Bank","Dach","Bank","Dach","Stmk","Bush","Stra","Wand"},   
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Haus","Haus","Haus","ITur","Stra","Stra","Cwal","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Bush","Bush","Stmk","Dach","Dach","Dach","Stmk","Bush","Bush","Stra","Wand"},     
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Haus","Haus","Haus","Haus","Stra","Stra","Cwal","Gass","Haus","ITur","Haus","Haus","Gass","Haus","ITur","Haus","Haus","Stra","Stra","Pers","Bush","Bush","Bush","Stmk","Stra","Stmk","Bush","Bush","Bush","Stra","Wand"},
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Stra","Haus","Haus","Stra","Stra","Stra","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Bush","Bush","Bush","Stra","Stra","Stra","Bush","Bush","Bush","Stra","Wand"},  
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Bush","Plas","Plas","Plas","Stra","Plas","Plas","Plas","Bush","Stra","Wand"},      
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Pers","Stra","Stra","Stra","Stra","Stra","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Bush","Plas","Wass","Plas","Stra","Plas","Wass","Plas","Bush","Stra","Wand"},       
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Stra","Stra","Stra","Stra","Haus","Haus","Cwal","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Stra","Stra","Stra","Bush","Plas","Plas","Plas","Stra","Plas","Plas","Plas","Bush","Stra","Wand"},       
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Stra","Stra","Stra","Stra","Haus","Haus","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Bush","Pers","Stra","Stra","Stra","Stra","Stra","Pers","Bush","Stra","Wand"},       
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Stra","Stra","Stra","Stra","ITur","Haus","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Bush","Stra","Stra","Stra","Stra","Stra","Stra","Pers","Bush","Stra","Wand"},      
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Stra","Stra","Stra","Pers","Haus","Haus","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","ITur","Stra","Stra","Stra","Bush","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Bush","Stra","Wand"},      
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Stra","Stra","Stra","Stra","Haus","Haus","Cwal","Gass","Haus","Haus","ITur","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Bush","Stra","Stra","Pers","Stra","Pers","Stra","Stra","Bush","Stra","Wand"},       
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Gass","Ofen","Pers","Stra","TrAK","Gass","Haus","TrSK","Pers","Haus","Stra","Stra","Stra","Bush","Bush","Bush","Bush","Stra","Bush","Bush","Bush","Bush","Stra","Wand"},       
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Pers","Plas","Plas","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Wand"},     
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Stra","Stra","Stra","Stra","Stra","Pers","Cwal","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Plas","Wass","Plas","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Blck","Wand"},   
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Stra","Stra","Stra","Stra","Stra","Hinw","Tga1","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Plas","Wass","Plas","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Blck","Wand"},    
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Stra","Stra","Stra","Stra","Stra","Pers","Cwal","Pers","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Plas","Plas","Plas","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Wand"}, 
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Gass","Haus","Haus","ITur","Haus","Gass","Haus","Haus","ITur","Haus","Stra","Stra","Stra","Haus","ITur","Haus","Haus","Gass","Haus","ITur","Haus","Haus","Stra","Wand"},     
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Wand"},      
        {"Wand","Ship","Ship","Ship","Ship","Ship","Ship","Wass","Stha","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Pers","Stra","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Wand"},       
        {"Wand","Ship","Star","Steg","Steg","Steg","Ship","Ship","Stha","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Wand"},      
        {"Wand","Ship","Pers","Steg","Steg","Heal","Ship","Ship","Stha","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Stra","Stra","Stra","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Gass","Stra","Wand"},       
        {"Wand","Ship","Ship","Ship","Steg","Ship","Ship","Wass","Stha","Stra","Stra","Pers","Stra","Stra","Stra","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Wand"},     
        {"Wand","Wass","Wass","Wass","Hinw","Wass","Wass","Wass","Stha","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Wand"},      
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Haus","Haus","Haus","VTur","Haus","Haus","Cwal","Gass","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Stra","Stra","Haus","Haus","Haus","Haus","Gass","Haus","Haus","Haus","Haus","Stra","Wand"},          
        {"Wand","Wass","Wass","Stha","Pers","Stha","Stha","Stha","Stha","Haus","Schi","Bode","Bode","Bode","Bomb","Cwal","Gass","Haus","Haus","ITur","Haus","Gass","Haus","Haus","ITur","Haus","Stra","Stra","Stra","Haus","Haus","ITur","Haus","Gass","Haus","Haus","ITur","Haus","Stra","Wand"},        
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Haus","Schi","Bode","Bode","Bode","Bomb","Cwal","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Wand"},        
        {"Wand","Wass","Wass","Stha","Stha","Stha","Stha","Stha","Stha","Haus","Bode","Bode","Bode","Bode","Bode","Cwal","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Wand"},      
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Haus","Swor","Bode","Bode","Bode","Lmax","Cwal","Stra","Pers","Stra","Stra","Pers","Stra","Stra","Pers","Stra","Stra","Pers","Stra","Pers","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Wand"},       
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Stha","Haus","Swor","Bode","Coin","Bode","Bode","Cwal","Cwal","TrSA","Cwal","Cwal","TrSS","Cwal","Cwal","TrSB","Cwal","Cwal","Cwal","Blck","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Wand"},
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stra","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Wand"},
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},

          };
            return Mapone;
        }
        public string[,] Maps4()
        {
            string[,] Mapone = new string[40, 40]
          {
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},
        {"Wand","Wass","Stha","Stha","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Wand"},
        {"Wand","Wass","Stha","Stha","Hinw","OTur","Bode","Schi","Swor","Heal","Bode","Cwal","Mobl","Mobl","Bode","Bode","Trep","Trep","Trep","Trep","Bode","Bode","Cwal","Bedh","Heal","Bode","Mobl","Cwal","Keys","Bode","Mobl","Mobl","Cwal","Bush","Bode","Bode","Bode","Bush","Cwal","Wand"},       
        {"Wand","Wass","Stha","Stha","Stha","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Trep","Trep","Trep","Trep","Bode","Bode","Cwal","Bedb","Bode","Bode","Mobl","Cwal","Mobl","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Wand"},       
        {"Wand","Wass","Stha","Stha","Stha","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Cwal","Cwal","Cwal","Bode","Bode","Cwal","Bedb","Bode","Bode","Bode","Cwal","Bedh","Bedb","Bedb","Bode","Cwal","Bode","Bode","Pers","Bode","Bode","Cwal","Wand"},     
        {"Wand","Wass","Stha","Stha","Stha","Cwal","Bode","Bode","Bode","Mobl","Mobl","Cwal","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Bedh","Bedb","Bedb","Bode","Cwal","Bode","Pers","Mobl","Pers","Bode","Cwal","Wand"},     
        {"Wand","Wass","Stha","Stha","Stha","Cwal","Mobl","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Mobl","Bode","Bode","Bode","Cwal","Bode","Pers","Mobl","Pers","Bode","Cwal","Wand"},      
        {"Wand","Wass","Stha","Stha","Stha","Cwal","Mobl","Bode","Bode","Bode","Bode","OTur","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Bode","Pers","Mobl","Pers","Bode","Cwal","Wand"},       
        {"Wand","Wass","Stha","Stha","Stha","Cwal","Cwal","Cwal","Cwal","OTur","Cwal","Cwal","Mobl","Mobl","Mobl","Mobl","Mobl","Mobl","Bode","Cwal","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Bode","Pers","Mobl","Pers","Bode","Cwal","Wand"},      
        {"Wand","Wass","Stha","Stha","Stha","Cwal","Bode","Bode","Bode","Hinw","Mobl","Cwal","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Bode","Pers","Mobl","Pers","Bode","Cwal","Wand"},        
        {"Wand","Wass","Stha","Stha","Stha","Cwal","Bode","Bode","Bode","Bode","Mobl","Cwal","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cwal","Cwal","OTur","Cwal","Cwal","OTur","Cwal","Cwal","Cwal","Cwal","OTur","Cwal","Cwal","Cwal","Bode","Pers","Mobl","Pers","Bode","Cwal","Wand"},     
        {"Wand","Wass","Stha","Stha","Stha","Cwal","Bedh","Bedb","Bedb","Bode","Bode","Cwal","Cwal","OTur","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Bode","Bode","Bode","Bode","Bode","Mobl","Mobl","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Wand"},     
        {"Wand","Wass","Wass","Stha","Stha","Cwal","Schi","Bode","Bode","Bode","Bode","Cwal","Bode","Hinw","Cwal","Bush","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Wand"},        
        {"Wand","Wass","Wass","Stha","Stha","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Fire","Cwal","Bode","Bode","Bode","Bode","Bode","OTur","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cwal","Bush","Bode","Bode","Bode","Bush","Cwal","Wand"},     
        {"Wand","Wass","Wass","Stha","Stha","Cwal","Bedh","Bedb","Bedb","Bode","Bode","Cwal","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","ETur","Cwal","Cwal","Cwal","Cwal","Cwal","OTur","Cwal","Cwal","Cwal","Cwal","Wand"},       
        {"Wand","Wass","Wass","Stha","Stha","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Fire","Bode","Cwal","Bode","Bode","Mobl","Mobl","Bode","Cwal","Mobl","Mobl","Bode","Bode","Bode","Bode","Cwal","Hinw","Trep","Trep","Trep","Tepp","Pers","Bode","Pers","Bode","Bode","Cwal","Wand"},     
        {"Wand","Wass","Wass","Stha","Wass","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Cwal","Cwal","Bode","Mobl","Mobl","Bode","Cwal","Bode","Tepp","Tepp","Tepp","Bode","Bode","Cwal","Trep","Trep","Trep","Trep","Tepp","Tepp","Bode","Bode","Bode","Bode","Cwal","Wand"},    
        {"Wand","Wass","Wass","Stha","Wass","Cwal","Bedh","Bedb","Bedb","Bode","Bode","Cwal","Bode","Fire","Cwal","Fire","Bode","Mobl","Mobl","Bode","Cwal","Bode","Tepp","Tepp","Tepp","Bode","Bode","Cwal","Cwal","Cwal","Cwal","Cwal","Pers","Tepp","Bode","Bode","Bode","Pers","Cwal","Wand"},     
        {"Wand","Wass","Wass","Stha","Wass","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Cwal","Cwal","Bode","Mobl","Mobl","Bode","Cwal","Bode","Tepp","Mobl","Tepp","Tepp","Kome","OTur","Tepp","Tepp","Tepp","Tepp","Tepp","Tepp","Tepp","Tepp","Bode","Bode","Bode","Wand"},     
        {"Wand","Wass","Stha","Stha","Cwal","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Fire","Bode","Cwal","Bode","Bode","Mobl","Mobl","Bode","Cwal","Bode","Mayo","Mobl","Tepp","Mobl","Kome","OTur","Tepp","Tepp","Tepp","Tepp","Tepp","Tepp","Tepp","Tepp","Bode","Bode","Star","Wand"},      
        {"Wand","Wass","Stha","Stha","Ende","Cwal","Bedh","Bedb","Bedb","Bode","Bode","Cwal","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Tepp","Mobl","Tepp","Tepp","Tepp","Cwal","Cwal","Cwal","Cwal","Cwal","Pers","Tepp","Bode","Bode","Bode","Pers","Cwal","Wand"},     
        {"Wand","Wass","Stha","Stha","Cwal","Cwal","Swor","Bode","Bode","Bode","Bode","Cwal","Bode","Fire","Cwal","Heal","Bode","Bode","Bode","Bode","Cwal","Bode","Tepp","Tepp","Tepp","Bode","Bode","Cwal","Trep","Trep","Trep","Trep","Tepp","Tepp","Bode","Bode","Bode","Bode","Cwal","Wand"}, 
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Cwal","Bush","Bode","Bode","Bode","Bode","Cwal","Mobl","Tepp","Tepp","Tepp","Bode","Bode","Cwal","Hinw","Trep","Trep","Trep","Tepp","Pers","Bode","Pers","Bode","Bode","Cwal","Wand"},     
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bedh","Bedb","Bedb","Bode","Bode","Cwal","Cwal","OTur","Cwal","Cwal","Cwal","Cwal","OTur","Cwal","Cwal","Mobl","Bode","Bode","Bode","Mobl","Mobl","Cwal","ETur","Cwal","Cwal","Cwal","Cwal","Cwal","OTur","Cwal","Cwal","Cwal","Cwal","Wand"},       
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Schi","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Bode","Cwal","Bush","Plas","Plas","Plas","Plas","Plas","Plas","Bush","Cwal","Wand"},    
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Mobl","Mobl","Bode","Cwal","Heal","Plas","Plas","Plas","Plas","Plas","Plas","Plas","Cwal","Wand"},      
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bedh","Bedb","Bedb","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Bode","Etra","Etra","Etra","Etra","Etra","Hinw","OTur","Bode","Bode","Bode","Bode","Cwal","Plas","Plas","Wass","Wass","Wass","Wass","Plas","Plas","Cwal","Wand"},      
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Coin","Bode","Bode","Coin","Cwal","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Plas","Plas","Wass","Wass","Wass","Wass","Plas","Plas","Cwal","Wand"},     
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Bode","Cwal","Plas","Plas","Wass","Wass","Wass","Wass","Plas","Plas","Cwal","Wand"},     
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bedh","Bedb","Bedb","Bode","Bode","Cwal","Etra","Bode","Etra","Etra","Cwal","Schi","Schi","Schi","Cwal","Schi","Cwal","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Plas","Plas","Wass","Wass","Wass","Wass","Plas","Plas","Cwal","Wand"},   
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Swor","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Etra","Cwal","Bode","Bode","Bode","Cwal","Bode","Cwal","Bode","OTur","Bode","Bode","Bode","Bode","Cwal","Bush","Plas","Wass","Wass","Wass","Wass","Plas","Bush","Cwal","Wand"},      
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Etra","Bode","Bode","OTur","Bode","Bode","Bomb","Cwal","Bode","VTur","Bode","Cwal","Cwal","Cwal","Cwal","Bode","Cwal","Plas","Plas","Wass","Wass","Wass","Wass","Plas","Plas","Cwal","Wand"},      
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bedh","Bedb","Bedb","Bode","Bode","Cwal","Etra","Bode","Etra","Bode","Cwal","Bode","Bode","Bode","Cwal","Bode","Cwal","Bode","OTur","Bode","Bode","Bode","Bode","Cwal","Plas","Plas","Wass","Wass","Wass","Wass","Plas","Plas","Cwal","Wand"},     
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Swor","Swor","Swor","Cwal","Swor","Cwal","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Plas","Mobl","Mobl","Wass","Wass","Wass","Plas","Plas","Cwal","Wand"},       
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bode","Bode","Bode","Bode","Bode","Cwal","Bode","Etra","Bode","Etra","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Bode","Cwal","Plas","Plas","Wass","Wass","Wass","Wass","Plas","Plas","Cwal","Wand"}, 
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bedh","Bedb","Bedb","Bode","Bode","Cwal","Bode","Bode","Etra","Bode","Cwal","Bode","Etra","Etra","Etra","Etra","Etra","Bode","Cwal","Bode","Bode","Bode","Bode","Cwal","Plas","Plas","Wass","Wass","Wass","Wass","Plas","Plas","Cwal","Wand"},    
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Schi","Bode","Bode","Bode","Bode","Cwal","Bode","Etra","Etra","Hinw","OTur","Bode","Bode","Bode","Bode","Bode","Bode","Hinw","OTur","Bode","Bode","Bode","Bode","Cwal","Plas","Plas","Plas","Plas","Plas","Plas","Plas","Plas","Cwal","Wand"},
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Bode","Bode","Bode","Mobl","Mobl","Cwal","Bode","Bode","Bode","Bode","Cwal","Bode","Etra","Etra","Etra","Etra","Etra","Bode","Cwal","Bode","Bode","Mobl","Mobl","Cwal","Bush","Plas","Plas","Plas","Plas","Plas","Plas","Bush","Cwal","Wand"},  
        {"Wand","Wass","Wass","Wass","Wass","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Wand"},
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},

          };
            return Mapone;
        }
        public string[,] Maps5()
        {
            string[,] Mapone = new string[40, 40]
          {
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},     
        {"Wand","Wass","Stha","Wass","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Gitt","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Bedh","Bedb","Bedb","Steg","Steg","Steg","Steg","Trep","Trep","Trep","Kome","Wand"},     
        {"Wand","Stha","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Stha","Stha","Cwal","Pers","Stha","Stha","Cwal","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Trep","Trep","Trep","Trep","Wand"},       
        {"Wand","Stha","Stha","Stha","Star","Stha","Stha","Stha","Stha","Hinw","Stha","Stha","Stha","Stha","Stha","Sewe","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Fire","Stha","Cwal","Bedh","Bedb","Bedb","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Wand"},      
        {"Wand","Stha","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Stha","Stha","Stha","Cwal","Stha","Sewe","Stha","Cwal","Cwal","Stha","Cwal","Cwal","Stha","Stha","Stha","Stha","Stha","Cwal","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Wand"},      
        {"Wand","Wass","Wass","Wass","Cwal","Leve","Stha","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Sewe","Stha","Cwal","Pers","Stha","Stha","Cwal","Stha","Cwal","Cwal","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Mobl","Mobl","Steg","Steg","Steg","Steg","Steg","Steg","Wand"},     
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Swor","Cwal","Heal","Stha","Stha","Stha","Cwal","Stha","Sewe","Stha","Cwal","Pers","Fire","Stha","Cwal","Stha","Cwal","Pers","Stha","Stha","Cwal","Schi","Schi","Cwal","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Wand"},  
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Swor","Cwal","Stha","Stha","Stha","Stha","Cwal","Stha","Sewe","Stha","Cwal","Stha","Stha","Stha","Cwal","Stha","Cwal","Stha","Fire","Stha","Rock","Steg","Steg","Cwal","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Wand"},     
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Stha","Cwal","Stha","Sewe","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Stha","Stha","Stha","Stha","Cwal","Steg","Steg","Cwal","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Steg","Wand"},      
        {"Wand","Wass","Wass","Wass","Cwal","OTur","Cwal","Cwal","Cwal","Cwal","Cwal","Pers","Cwal","Cwal","Stha","Sewe","Stha","Cwal","TrAK","Cwal","Tga1","Hinw","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Steg","Hinw","OTur","Steg","Steg","Steg","Steg","Cwal","Cwal","OTur","Cwal","Wand"},     
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Sewe","Stha","Cwal","Pers","Stha","Hinw","Cwal","Stha","Cwal","TrSK","Cwal","Stha","Cwal","Steg","Steg","Cwal","Steg","Steg","Steg","Cwal","Cwal","Stha","Kome","Stha","Wand"},    
        {"Wand","Wass","Wass","Wass","Cwal","Sewe","Sewe","Sewe","Sewe","Sewe","Stha","Sewe","Sewe","Cwal","Stha","Sewe","Stha","Stha","Stha","Fire","Stha","Cwal","Stha","Cwal","Pers","Fire","Stha","Cwal","Leve","Steg","Cwal","Steg","Steg","Steg","Fire","Cwal","Stha","Stha","Stha","Wand"},      
        {"Wand","Wass","Wass","Wass","Cwal","Sewe","Sewe","Sewe","Gift","Sewe","Stha","Sewe","Gift","Cwal","Stha","Sewe","Stha","Cwal","Stha","Stha","Stha","Cwal","Stha","Cwal","Stha","Stha","Stha","Cwal","Steg","Bomb","Cwal","Mobl","Mobl","Steg","Cwal","Cwal","Stha","Stha","Stha","Wand"},     
        {"Wand","Wass","Wass","Wass","Cwal","Sewe","Sewe","Sewe","Gift","Stha","Stha","Sewe","Gift","Cwal","Stha","Sewe","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Cwal","Cwal","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Stha","Stha","Wand"},      
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Stha","Stha","Stha","Sewe","Sewe","Gift","Cwal","Cwal","Gitt","LTur","Cwal","PHea","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Hinw","Gift","Stha","Gift","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Wand"},     
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Gift","Sewe","Gift","Sewe","Sewe","Sewe","Gift","Cwal","Stha","Sewe","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Gift","Gift","Gift","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Wand"},   
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Gift","Sewe","Gift","Sewe","Stha","Stha","Stha","Cwal","Stha","Sewe","Stha","Cwal","Pers","Stha","Stha","Cwal","Stha","Stha","Stha","Cwal","Stha","Gift","Gift","Gift","Stha","Cwal","Stha","Stha","Pers","Stha","Pers","Stha","Cwal","Wand"},        
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Gift","Stha","Stha","Stha","Stha","Sewe","Stha","Cwal","Stha","Sewe","Stha","Cwal","Pers","Fire","Stha","Cwal","Stha","Fire","Stha","Cwal","Stha","Gift","Gift","Gift","Stha","Cwal","Pers","Stha","Stha","Stha","Stha","Pers","Cwal","Wand"},    
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Stha","Sewe","Gift","Sewe","Sewe","Stha","Cwal","Stha","Sewe","Stha","Cwal","Stha","Stha","Pers","Cwal","Stha","Stha","Stha","Cwal","Stha","Gift","Gift","Gift","Stha","Cwal","Pers","Stha","Fire","Stha","Fire","Pers","Cwal","Wand"},        
        {"Wand","Wass","Wass","Wass","Cwal","Sewe","Sewe","Sewe","Sewe","Gift","Stha","Stha","Stha","Cwal","Stha","Sewe","Stha","Cwal","Stha","Stha","Stha","Cwal","Stha","Pers","Stha","Cwal","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Wand"},      
        {"Wand","Wass","Wass","Wass","Cwal","Sewe","Gift","Stha","Stha","Stha","Stha","Sewe","Gift","Cwal","Stha","Sewe","Stha","Cwal","Cwal","Cwal","Stha","Cwal","Cwal","Cwal","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Cwal","Cwal","Wand"},    
        {"Wand","Wass","Wass","Wass","Cwal","Sewe","Gift","Stha","Sewe","Gift","Sewe","Sewe","Gift","Cwal","Stha","Sewe","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Wand"},        
        {"Wand","Wass","Wass","Wass","Cwal","Sewe","Sewe","Stha","Sewe","Gift","Sewe","Sewe","Gift","Cwal","Stha","Sewe","Stha","Sewe","Sewe","Sewe","Sewe","Sewe","Sewe","Sewe","Sewe","Gitt","Sewe","Sewe","Sewe","Sewe","Sewe","Sewe","Sewe","Sewe","Sewe","Sewe","Sewe","Sewe","Gitt","Wand"},     
        {"Wand","Wass","Wass","Wass","Cwal","Sewe","Sewe","Stha","Sewe","Sewe","Sewe","Sewe","Gift","Cwal","Stha","Sewe","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","LTur","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Wand"},     
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Sewe","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Cwal","Cwal","Wand"},       
        {"Wand","Wass","Wass","Wass","Cwal","Cwal","Cwal","Cwal","Hinw","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Sewe","Stha","Cwal","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Cwal","Gift","Cwal","Gift","Stha","Stha","Stha","Stha","Cwal","Stha","Cwal","Stha","Cwal","Cwal","Wand"},      
        {"Wand","Wass","Wass","Wass","Cwal","Cwal","Cwal","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Sewe","Stha","Cwal","Stha","Cwal","Stha","Cwal","Stha","Cwal","Stha","Stha","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Cwal","Stha","Cwal","Stha","Cwal","Cwal","Wand"},   
        {"Wand","Wass","Wass","Wass","Cwal","Cwal","Cwal","Cwal","Rock","Cwal","Cwal","Cwal","Stha","Cwal","Stha","Sewe","Stha","Cwal","Stha","Cwal","Stha","Etra","Stha","Cwal","Cwal","Cwal","Stha","Gift","Stha","Cwal","Stha","Stha","Stha","Etra","Stha","Cwal","Stha","Cwal","Cwal","Wand"},    
        {"Wand","Wass","Wass","Wass","Cwal","Cwal","Cwal","Cwal","Stha","Cwal","Cwal","Cwal","Stha","Cwal","Stha","Sewe","Stha","Cwal","Stha","Cwal","Stha","Cwal","Cwal","Cwal","Gift","Cwal","Stha","Cwal","Stha","Cwal","Stha","Cwal","Stha","Cwal","Stha","Cwal","Stha","Cwal","Cwal","Wand"},      
        {"Wand","Wass","Wass","Wass","Cwal","Cwal","Cwal","Cwal","Rock","Cwal","Cwal","Cwal","Stha","Cwal","Stha","Sewe","Stha","Cwal","Bomb","Cwal","Stha","Cwal","Keys","Cwal","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Etra","Stha","Cwal","Stha","Cwal","Stha","Cwal","Cwal","Wand"},    
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Sewe","Stha","Cwal","Cwal","Cwal","Stha","Cwal","Stha","Stha","Stha","Cwal","Stha","Cwal","Stha","Cwal","Etra","Cwal","Stha","Cwal","Cwal","Cwal","Stha","Cwal","Cwal","Wand"},      
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Sewe","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Cwal","Cwal","Wand"},     
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Stha","Fire","Stha","Stha","Cwal","Stha","Stha","Stha","Sewe","Stha","Cwal","Cwal","Cwal","Cwal","Stha","Stha","Stha","Stha","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stha","Cwal","Gift","Cwal","Stha","Cwal","Cwal","Wand"},       
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Sewe","Stha","Cwal","Cwal","Cwal","Cwal","VTur","Cwal","Cwal","Stha","Stha","Stha","Cwal","Stha","Gift","Stha","Cwal","Stha","Cwal","Cwal","Cwal","Stha","Cwal","Cwal","Wand"},     
        {"Wand","Wass","Wass","Sewe","Cwal","Stha","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Stha","Stha","Cwal","Schi","Stha","Stha","Stha","Cwal","Cwal","Stha","Cwal","Stha","Stha","Stha","Cwal","Stha","Stha","Stha","Stha","Stha","Cwal","Stha","Cwal","Cwal","Wand"},    
        {"Wand","Wass","Wass","Sewe","Sewe","Sewe","Stha","Sewe","Sewe","Sewe","Sewe","Gitt","Sewe","Sewe","Sewe","Sewe","Stha","Cwal","Bomb","Stha","Stha","Stha","Cwal","Cwal","Stha","Cwal","Cwal","Cwal","Stha","Cwal","Stha","Cwal","Stha","Stha","Hinw","Cwal","Stha","Cwal","Cwal","Wand"},     
        {"Wand","Wass","Wass","Sewe","Cwal","Stha","Stha","Stha","Cwal","Cwal","Cwal","Cwal","Stha","Stha","Stha","Sewe","Stha","Cwal","Swor","Stha","Stha","Stha","Cwal","Cwal","Stha","Cwal","Stha","Cwal","Stha","Stha","Stha","Cwal","Stha","Cwal","Stha","Stha","Stha","Cwal","Cwal","Wand"},       
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Fire","Stha","Stha","Stha","Stha","Cwal","Cwal","Stha","Stha","Sewe","Stha","Cwal","Cwal","Cwal","Ende","Cwal","Cwal","Heal","Stha","Cwal","Stha","Etra","Stha","Cwal","Stha","Gift","Stha","Cwal","Stha","Stha","Stha","Cwal","Cwal","Wand"},      
        {"Wand","Wass","Wass","Wass","Cwal","Stha","Stha","Stha","Cwal","Stha","Mboo","Cwal","Hinw","Stha","Cwal","Gitt","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Wand"},
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},

          };
            return Mapone;
        }
        public string[,] Maps6()
        {
            string[,] Mapone = new string[40, 40]
          {
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},       
        {"Wand","Wass","Wass","Stha","Star","Cwal","Gass","Gass","Gass","Gass","Stra","Stra","Cwal","Dach","Cwal","Stra","Cwal","Wass","Stra","Gass","Gass","Stra","Gass","Gass","Cwal","Wass","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wand"},     
        {"Wand","Wass","Wass","Stha","Haus","Cwal","Gass","Haus","Gass","Haus","Stra","Stra","Bush","PHea","Bush","Stra","Cwal","Wass","Stra","Haus","Haus","Stra","Haus","Haus","Cwal","Wass","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wand"},        
        {"Wand","Wass","Wass","Stha","Stra","Cwal","Stra","Stra","Stra","Stra","Stra","Stra","Bush","Stra","Bush","Stra","Cwal","Wass","Stra","Stra","Stra","Stra","Kome","Stra","Cwal","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Wand"},      
        {"Wand","Wass","Wass","Stha","Stra","Tga1","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Kome","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Kome","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Ende","Wand"},      
        {"Wand","Wass","Wass","Stha","Stra","Cwal","Stra","Stra","Stra","Stra","Pers","Stra","Stra","Stra","Stra","Stra","Cwal","Wass","Stra","Stra","Stra","Stra","Kome","Stra","Cwal","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Wand"},     
        {"Wand","Wass","Ship","Kome","Kome","Cwal","Gass","Haus","Gass","Haus","Stra","Stra","Haus","Gass","Haus","Gass","Cwal","Wass","Stra","Haus","Haus","Stra","Haus","Haus","Cwal","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},    
        {"Wand","Wass","Stha","Stha","Stra","Cwal","Gass","Gass","Gass","Gass","Stra","Stra","Gass","Gass","Gass","Gass","Cwal","Wass","Stra","Gass","Gass","Stra","Gass","Gass","Cwal","Wass","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Wald","Wald","Wand"},     
        {"Wand","Wass","Wass","Stha","Stra","Cwal","Gass","Haus","Gass","Haus","Stra","Stra","Haus","Gass","Haus","Gass","Cwal","Wass","Stra","Haus","Haus","Stra","Haus","Haus","Cwal","Wass","Wald","Heal","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Wand"},      
        {"Wand","Wass","Wass","Stha","Haus","Cwal","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Wass","Stra","Gass","Gass","Pers","Stra","Haus","Cwal","Wass","Wald","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wand"},     
        {"Wand","Wass","Wass","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stra","Cwal","Cwal","Cwal","Cwal","Cwal","Wass","Stra","Haus","Haus","Stra","Stra","Haus","Cwal","Wass","Wald","Wald","Wald","Gras","Wald","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wand"},       
        {"Wand","Wass","Wass","Cwal","Schi","Stra","Swor","Cwal","Wass","Wass","Stra","Stra","Wass","Wass","Wass","Wass","Wass","Wass","Stra","Stra","Stra","Stra","Haus","Haus","Cwal","Wass","Wass","Wass","Wass","Gras","Wass","Gras","Wass","Gras","Gras","Gras","Gras","Dorn","Wald","Wand"},  
        {"Wand","Wass","Wass","Cwal","Schi","Stra","Swor","Cwal","Cwal","Wass","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Bomb","Gras","Gras","Wald","Gras","Gras","Gras","Wass","Wald","Wald","Wald","Gras","Dorn","Wald","Wand"},      
        {"Wand","Wass","Wass","Cwal","Stra","Stra","Stra","Stra","Cwal","Wass","Stra","Stra","Stra","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Cwal","Bomb","Gras","Gras","Rock","Gras","Gras","Gras","Wass","Wald","Gras","Gras","Gras","Gras","Wald","Wand"},     
        {"Wand","Wass","Wass","Cwal","Cwal","OTur","Cwal","Cwal","Cwal","Wass","Stra","Stra","Pers","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Cwal","Schi","Gras","Wald","Wald","Wald","Wald","Gras","Wass","Wald","Gras","Wald","Wald","Gras","Wald","Wand"},     
        {"Wand","Wass","Wass","Cwal","Stra","Stra","Stra","Stra","Stra","Stra","Kome","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Gras","Gras","Wald","Dorn","Gras","Gras","Gras","Wass","Wald","Dorn","Gras","Gras","Gras","Wald","Wand"},   
        {"Wand","Wass","Wass","Cwal","Gras","Gras","Gras","Cwal","Cwal","Wass","Stra","Stra","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Gass","Cwal","Wald","Wald","Wald","Gras","Gras","Dorn","Gras","Wass","Wald","Gras","Gras","Gras","Wald","Wald","Wand"},       
        {"Wand","Wass","Wass","Cwal","Gras","Gras","Gras","Gras","Cwal","Wass","Stra","Stra","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Gass","Haus","Gass","Cwal","Dorn","Gras","Dorn","Gras","Wass","Wass","Wass","Wass","Wald","Wald","Gras","Gras","Gift","Wald","Wand"},   
        {"Wand","Wass","Wass","Cwal","Gras","Gras","Gras","Cwal","Cwal","Wass","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Gras","Dorn","Gras","Gras","Wass","Wald","Wald","Wald","Wald","Gras","Gras","Gras","Gift","Wald","Wand"},       
        {"Wand","Wass","Wass","Cwal","Swor","Gras","Gras","Cwal","Wass","Wass","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Stra","Cwal","Sewe","Gras","Gras","Sewe","Sewe","Wald","Heal","Lmax","Wald","Gras","Gras","Gift","Gift","Wald","Wand"},    
        {"Wand","Wass","Wass","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Stra","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Cwal","Sewe","Gras","Sewe","Sewe","Sewe","Wald","Gras","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Wand"},      
        {"Wand","Wass","Wass","Pali","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Fweg","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Swor","Pali","Dorn","Kome","Dorn","Dorn","Wass","Wald","Schi","Gras","Masd","Gras","Gras","Gras","Swor","Wald","Wand"},       
        {"Wand","Wass","Wass","Pali","Gras","Haus","Gras","Haus","Gras","Haus","Pers","Fweg","Gras","Haus","Gras","Haus","Gras","Haus","Gras","Haus","Gras","Haus","Gras","Haus","Pali","Gras","Gras","Gras","Gras","Wass","Wald","Gras","Mboo","Wald","Gras","Gras","Gras","Gras","Wald","Wand"},       
        {"Wand","Wass","Wass","Pali","Gras","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Haus","Pali","Gras","Wald","Wald","Wald","Wass","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Wald","Wand"}, 
        {"Wand","Wass","Wass","Wass","Pali","Haus","Gras","Haus","Gras","Haus","Gras","Fweg","Gras","Haus","Gras","Haus","Gras","Haus","Gras","Haus","Fweg","Haus","Gras","Haus","Pali","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wald","Gras","Gras","Wald","Wand"},     
        {"Wand","Wass","Wass","Pali","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Fweg","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Fweg","Gras","Gras","Bomb","Pali","Gift","Gift","Gift","Gras","Gras","Gras","Stha","Gras","Gras","Wass","Wald","Wald","Gras","Wald","Wand"},    
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Gras","Gras","Fweg","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Gras","Fweg","Gras","Pers","Pali","Schi","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Wand"},      
        {"Wand","Wass","Wass","Pali","Gras","Cwal","Dach","Cwal","Wass","Gras","Gras","Fweg","Pers","Wass","Gras","Gras","Wass","Pers","Wass","Gras","Fweg","Gras","Gras","Gras","Pali","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wass","Gras","Wald","Gras","Wald","Wand"},      
        {"Wand","Wass","Wass","Pali","Gras","Bush","PHea","Bush","Wass","Wass","Wass","Fweg","Wass","Wass","Muhl","Muhl","Wass","Gras","Wass","Wass","Fweg","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Heal","Gras","Swor","Wass","Gras","Wald","Gras","Wald","Wand"},   
        {"Wand","Wass","Wass","Wass","Pali","Bush","Stra","Bush","Gras","Gras","Gras","Fweg","Gras","Gras","Muhl","Muhl","Wass","Fweg","Fweg","Fweg","Fweg","Gras","Gras","Gras","Pali","Wald","Wald","Wald","Wald","Gras","Wass","Gras","Gras","Gras","Wass","Gras","Wald","Gras","Wald","Wand"},    
        {"Wand","Wass","Wass","Pali","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Fweg","Pers","Fweg","Fweg","Fweg","Feld","Feld","Feld","Feld","Feld","Feld","Pali","Gras","Wald","Gras","Gras","Gras","Wass","Gras","Gras","Gras","Wass","Gras","Wald","Gras","Wald","Wand"},   
        {"Wand","Wass","Wass","Schi","Pali","Pers","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Fweg","Feld","Feld","Pers","Feld","Feld","Feld","Pali","Gras","Wald","Gras","Gras","Gras","Wass","Wass","Gras","Wass","Wass","Gras","Wald","Gras","Wald","Wand"},     
        {"Wand","Wass","Wass","Gras","Pali","Gras","Gras","Gras","Feld","Feld","Feld","Feld","Feld","Feld","Gras","Gras","Wass","Fweg","Feld","Feld","Feld","Feld","Feld","Feld","Pali","Gras","Dwal","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Wand"},     
        {"Wand","Wass","Wass","Gras","Gras","Pali","Gras","Gras","Feld","Feld","Feld","Feld","Feld","Feld","Gras","Gras","Wass","Fweg","Wass","Wass","Wass","Wass","Wass","Pali","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Wald","Wand"},      
        {"Wand","Wass","Wass","Gras","Gras","Gras","Pali","Gras","Feld","Feld","Feld","Feld","Feld","Feld","Gras","Gras","Wass","Fweg","Gras","Gras","Gras","Gras","Pali","Gras","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Wand"},      
        {"Wand","Wass","Wass","Wass","Gras","Gras","Gras","Pali","Pali","Pali","Pali","Pali","Pali","Pali","Pali","Pali","Pali","Fweg","Pali","Pali","Pali","Pali","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Wand"},      
        {"Wand","Wass","Wass","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Kome","Gras","Fweg","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Gras","Gras","Dorn","Gras","Gras","Dorn","Gras","Wald","Gras","Gras","Gras","Wald","Wand"},       
        {"Wand","Wass","Wass","Wass","Wass","Gras","Gras","Feld","Pers","Feld","Feld","Feld","Feld","Gras","Gras","Kome","Gras","Kome","Feld","Feld","Feld","Feld","Feld","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Dorn","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Wand"},      
        {"Wand","Wass","Wass","Wass","Wass","Wass","Wass","Feld","Feld","Feld","Feld","Feld","Feld","Gras","Gras","Kome","Gras","Fweg","Feld","Feld","Feld","Feld","Feld","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wand"},
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},

          };
            return Mapone;
        }
    }
}
