using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GameofLifedanielT
{
    class Lvlfunk
    {
        public string[,] Maps()
        {
            string[,] Mapone = new string[40, 40]
          {
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},
        {"Wand","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Hinw","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Hinw","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Wald","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Gift","Wald","Gift","Wald","Gift","Wald","Gras","Wass","Wass","Wass","Wass","Gras","Wass","Wass","Wass","Gras","Wand"},
        {"Wand","Gras","Hinw","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Heal","Wald","Wald","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Bomb","Heal","Wald","Gift","Wald","Gift","Wald","Gras","Wald","Gras","Wass","Gras","Gras","Gras","Gras","Wass","Schi","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Bomb","Wald","Gift","Wald","Gras","Wald","Gras","Wald","Gras","Wass","Gras","Wass","Wass","Wass","Wass","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Gift","Wald","Gras","Wald","Gras","Wald","Gras","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Wald","Wald","Gras","VTur","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wass","Gras","Wass","Wass","Wass","Wass","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Rock","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gift","Gift","Wald","Gras","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Wass","Gras","Wass","Keys","Gras","Gras","Gras","Wass","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Rock","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Heal","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Wald","Star","Wald","Wald","Gras","Hinw","Gras","Gift","Gras","Gift","Gras","Gift","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gift","Gras","Gras","Wald","Gras","Wald","Wald","Gras","Hinw","Gras","Gift","Gras","Gift","Gras","Gras","Gras","VTur","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gift","Gras","Gras","Wald","Gras","Wald","Wald","Gras","Hinw","Gras","Gift","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Gift","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Wald","Wald","Gras","Gras","Gift","Gras","Gift","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gift","Gras","Gift","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Wald","OTur","Wald","Wald","Wald","Wald","OTur","Wald","Wand"},
        {"Wand","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","OTur","Wald","Wald","Wald","Wald","OTur","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Hinw","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","OTur","Wald","Wald","Wald","OTur","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","OTur","Wald","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Wass","Wass","Wass","Wass","Wass","Schi","Wass","Wald","Gift","Wald","Gift","Wald","Gras","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Wass","Wass","Wass","Wass","Wass","Gras","Wass","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Wass","Gras","Gras","Gras","Gras","Gras","Wass","Wald","Wald","Gift","Wald","Gras","Wald","Gift","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Wald","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Lmax","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Wand"},
        {"Wand","Wald","Wald","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wald","Gras","Wald","Gift","Wald","Gift","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","OTur","Wald","Wald","Wald","Wald","Wald","Wald","Wand"},
        {"Wand","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Heal","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Haus","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Keys","Gras","Gras","Gras","Gras","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Haus","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Wald","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Haus","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Haus","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gift","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Haus","Wass","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gift","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gift","Gift","Gift","Wald","Haus","Haus","Haus","Haus","Gras","Gras","Gras","Gras","Gras","OTur","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Gras","Gras","Gras","Haus","Wass","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Haus","Haus","Haus","Gras","Haus","Wass","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Wald","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Haus","Haus","Haus","Gras","Haus","Wass","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Gras","Hinw","Gras","Gras","Gras","Wald","Gras","Gras","Haus","Ende","Haus","Haus","Haus","Haus","Gras","Haus","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},

          };
            return Mapone;
        }
        public string[,] Maps2()
        {
            string[,] Mapone = new string[40, 40]
          {
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},
        {"Wand","Wald","Wald","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Wand","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Kome","Schi","Wand"},
        {"Wand","Wald","Wald","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Wand","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Kome","Gras","Wand"},
        {"Wand","Wald","Wald","Wald","Haus","Haus","Haus","Gras","Haus","Haus","Gras","Wand","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},   
        {"Wand","Wald","Heal","Gras","Gras","Pers","Gras","Gras","Gras","Gras","Gras","Wand","Wass","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},  
        {"Wand","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Pers","Wand","Wass","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},      
        {"Wand","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Star","Gras","Gras","OTur","Gras","Kome","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Haus","Haus","Haus","Haus","Pers","Gras","Gras","Gras","Gras","OTur","Gras","Kome","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Pers","Gras","Pers","Wand","Wass","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Gras","Gras","Gras","Gras","Gras","Haus","Haus","Haus","Gras","Wand","Wass","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Gras","Pers","Gras","Gras","Gras","Haus","Haus","Haus","Gras","Wand","Wass","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Swor","Haus","Gras","Gras","Gras","Haus","Haus","Haus","Gras","Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Gras","Gras","Gras","Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Ship","Ship","Ship","Ship","Ship","Ship","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Haus","Haus","Haus","Gras","Gras","Gras","Gras","Gras","Gras","Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Ship","Ende","Steg","Steg","Schi","Ship","Ship","Wass","Wass","Wass","Lava","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},   
        {"Wand","Wald","Haus","Haus","Haus","Gras","Gras","Pers","Gras","Gras","Gras","Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Ship","Pers","Steg","Steg","Heal","Ship","Ship","Wass","Wass","Wass","Lava","Lava","Wass","Wass","Wass","Wass","Wass","Wass","Wand"},
        {"Wand","Wald","Wand","Wand","Wand","OTur","OTur","Wand","Wand","Wand","Wand","Wand","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Ship","Ship","Ship","Steg","Ship","Ship","Wass","Wass","Cave","Cave","Lava","Lava","Cave","Cave","Cave","Cave","Cave","Cave","Wand"},
        {"Wand","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Steg","Wass","Wass","Wass","Wass","Cave","Bode","Lava","Lava","Lava","Cave","Swor","Rock","Bode","Cave","Wand"},
        {"Wand","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Heal","Kome","Cave","Bode","Bode","Haus","Haus","Haus","Cave","Bode","Lava","Lava","Lava","Cave","Gift","Cave","Bode","Cave","Wand"},
        {"Wand","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Bode","Cave","Bode","Bode","Haus","Haus","Haus","Cave","Bode","Lava","Lava","Bode","Cave","Gift","Cave","Bode","Cave","Wand"},     
        {"Wand","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Bode","Cave","Bode","Bode","Bode","Haus","Bode","Cave","Bode","Lava","Lava","Bode","Cave","Gift","Cave","Bode","Cave","Wand"},      
        {"Wand","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Swor","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Bode","Cave","Cave","Bode","Bode","Pers","Bode","Cave","Bode","Lava","Lava","Bode","Cave","Gift","Cave","Bode","Cave","Wand"}, 
        {"Wand","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Gras","Pers","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Bode","Cave","Cave","Cave","Cave","Bode","Bode","Bode","Bode","Lava","Lava","Bode","Cave","Hinw","Cave","Bode","Cave","Wand"}, 
        {"Wand","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Bode","Bode","Bode","Bode","Cave","Bode","Bode","Bode","Bode","Bode","Lava","Bode","Bode","Bode","Bode","Bode","Cave","Wand"},    
        {"Wand","Wass","Wass","Hinw","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Cave","Cave","Cave","Bode","Cave","Cave","Cave","Cave","Bode","Bode","Lava","Lava","Bode","Bode","Bode","Bode","Cave","Wand"},       
        {"Wand","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Wass","Cave","Gift","Gift","Bode","Bode","Cave","Cave","Cave","Cave","Bode","Bode","Lava","Lava","Bode","Bode","Bode","Bode","Cave","Wand"},     
        {"Wand","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Cave","Bode","Bode","Bode","Bode","Cave","Cave","Cave","Cave","Cave","Bode","Lava","Lava","Lava","Bode","Heal","Bode","Cave","Wand"},     
        {"Wand","Wald","Gras","Wald","Wald","Wald","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Gras","Kome","Bode","Bode","Bode","Keys","Cave","Cave","Cave","Cave","Cave","Bode","Bode","Lava","Lava","Cave","Cave","Bode","Cave","Wand"},     
        {"Wand","Wald","Gras","Wald","Wald","Wald","Wald","Gras","Wald","Wald","Wald","Wald","Heal","Wald","Gift","Gift","Gift","Wald","Wald","Wald","Wald","Cave","Cave","Cave","Cave","Cave","Cave","Bode","Bode","Cave","Cave","Cave","Bode","Lava","Lava","Lava","Lava","Bode","Cave","Wand"},    
        {"Wand","Wald","Gras","Wald","Gras","Gras","Wald","Gras","Wald","Bomb","Gras","Dwal","Gras","Wald","Gras","Gras","Gras","Wald","Wald","Gift","Gift","Cave","Cave","Cave","Cave","Cave","Cave","Bode","Bode","Cave","Cave","Cave","Cave","Cave","Cave","Lava","Lava","Bode","Cave","Wand"},      
        {"Wand","Wald","Gras","Wald","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Gras","Gras","Hinw","Gras","Gras","Wald","Wald","Gras","Gras","Kome","Bode","Bode","Cave","Cave","Bode","Bode","Bode","Bode","Bode","Bode","Cave","Bode","Bode","Lava","Lava","Bode","Cave","Wand"},       
        {"Wand","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Wald","Wald","Gras","Gift","Cave","Bode","Bode","Cave","Cave","Bode","Gift","Gift","Gift","Bode","Bode","Cave","Bode","Bode","Bode","Bode","Bode","Cave","Wand"},      
        {"Wand","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Wald","Gras","Gras","Dorn","Gras","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Gift","Cave","Bode","Bode","Bode","Bode","Bode","Gift","Gift","Gift","Gift","Bode","Hinw","Bode","Bode","Lava","Lava","Bode","Cave","Wand"},      
        {"Wand","Wald","Gras","Gras","Gras","Gras","Wald","Gras","Wald","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Gift","Gift","Gras","Gras","Cave","Bode","Bode","Bode","Bode","Bode","Gift","Gift","Gift","Bode","Bode","Hinw","Bode","Bode","Lava","Lava","Lava","Lava","Wand"},       
        {"Wand","Wald","Gras","Gras","Wald","Wald","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Gras","Gift","Gift","Gras","Heal","Cave","Cave","Cave","Cave","Cave","Bode","Bode","Bode","Bode","Bode","Bode","Cave","Bode","Bode","Lava","Lava","Lava","Lava","Wand"},      
        {"Wand","Wald","Hinw","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Dwal","Wald","Wald","Wald","Wald","Wald","Wald","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Wand"},        
        {"Wand","Wald","Gras","Gras","Gras","Dorn","Dorn","Gras","Wald","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Gras","Wald","Wald","Gras","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Swor","Swor","Bomb","Heal","Wand"}, 
        {"Wand","Wald","Gras","Gras","Gras","Gras","Dorn","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Wald","Wald","Gras","Rock","Kome","Bode","Bode","Bode","Bode","Bode","Bode","Bode","Cave","Cave","Cave","Kome","VTur","Kome","Bode","Bode","Bode","Wand"},      
        {"Wand","Wald","Gras","Gras","Gras","Dorn","Dorn","Gras","Gras","Gras","Wald","Wald","Wald","Wald","Wald","Gras","Wald","Gras","Gras","Gras","Gras","Cave","Bode","Cave","Cave","Cave","Cave","Cave","Bode","Bode","Bode","Bode","Bode","Bode","Cave","Bode","Bode","Bode","Bode","Wand"},     
        {"Wand","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Wald","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Cave","Lmax","Bode","Schi","Schi","Wand"},
        {"Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand","Wand"},

          };
            return Mapone;
        }
    }
}
